version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    # Uncomment the following if you want to persist models/data
    # volumes:
    #   - ollama_data:/root/.ollama

  app:
    build: .
    container_name: nomics-edu-app
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped
    volumes:
      - ./games_output:/app/games_output
    # Uncomment if you want to mount local files for development
    # volumes:
    #   - .:/app

#volumes:
#  ollama_data: 